/* ###*B*###
 * ERIKA Enterprise - a tiny RTOS for small microcontrollers
 *
 * Copyright (C) 2002-2014  Evidence Srl
 *
 * This file is part of ERIKA Enterprise.
 *
 * ERIKA Enterprise is free software; you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * version 2 as published by the Free Software Foundation,
 * (with a special exception described below).
 *
 * Linking this code statically or dynamically with other modules is
 * making a combined work based on this code.  Thus, the terms and
 * conditions of the GNU General Public License cover the whole
 * combination.
 *
 * As a special exception, the copyright holders of this library give you
 * permission to link this code with independent modules to produce an
 * executable, regardless of the license terms of these independent
 * modules, and to copy and distribute the resulting executable under
 * terms of your choice, provided that you also meet, for each linked
 * independent module, the terms and conditions of the license of that
 * module.  An independent module is a module which is not derived from
 * or based on this library.  If you modify this code, you may extend
 * this exception to your version of the code, but you are not
 * obligated to do so.  If you do not wish to do so, delete this
 * exception statement from your version.
 *
 * ERIKA Enterprise is distributed in the hope that it will be
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License version 2 for more details.
 *
 * You should have received a copy of the GNU General Public License
 * version 2 along with ERIKA Enterprise; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301 USA.
 * ###*E*### */

/*
 * Author: 2000-2004 Paolo Gai
 *         2009 Bernardo Dal Seno
 */


#ifndef __INCLUDE_PKG_EE_H__
#define __INCLUDE_PKG_EE_H__

#include "eecfg.h"

#include "ee_rtdruid_versions.h"

#if defined(__cplusplus)
extern "C" {
#endif

  /*
   *
   * CPU
   *
   */


#ifdef EE_TRICORE__
#include "ee_tc_cpu.h"
#endif /* EE_TRICORE__ */

/* Tricore TC26X || TC27x */
#if defined(EE_TRICORE__) && (defined(EE_TC26X__) || defined(EE_TC27X__))
//#include "ee_tc27x_mcu.h" steve
//#include "ee_tc2x5_board.h" steve
#endif


#ifdef __FP__
#include "ee_kernel.h"
#endif

#ifdef __EDF__
#include "ee_kernel.h"
#endif

#ifdef __FRSH__
#ifdef __SEM_FRSH__
#include "ee_sem.h"
#endif
#include "ee_kernel.h"
#endif

/* HR */
#ifdef __HR__
#include "ee_kernel.h"
#endif

/* OO */
#if defined(__OO_BCC1__) || defined(__OO_BCC2__) || defined(__OO_ECC1__) ||\
  defined(__OO_ECC2__) || defined(__AS_SC4__)
#include "ee_oo_kernel.h"
#include "ee_as_kernel.h"
/* Moved inline interrupt services inclusion here, because they need to see TP
   declarations */
#include "ee_oo_inline.h"

#ifdef EE_AS_IOC__
#include "ee_as_ioc.h"
/*                                 WARNING
   The following file SHALL be generated by IOC Generator: if you are using
   Erika IOC implementation without a generator you MUST provide it in your
   project root. */
#include "ioc_common.h"
#endif /* EE_AS_IOC__ */

#ifdef EE_AS_SCHEDULETABLES__
#include "ee_as_schedule_tables.h"
#endif /* EE_AS_SCHEDULETABLES__ */

#endif /* OO */

/* SEM */
#ifdef __SEM__
#include "ee_sem.h"
#endif

/* ALARMS */
#ifdef __ALARMS__
#include "ee_alarms.h"
#endif

/* RN */
#if defined(__RN__) || defined(EE_AS_RPC__)
#include "ee_rn.h"
#endif /* __RN__ || EE_AS_RPC__ */

  /*
   *
   * API
   *
   */

#include "ee_api.h"

  /*
   *
   * IRQ
   *
   */

#include "ee_irq.h"

/* Assert inclusion if enabled */
#ifdef __ASSERT__
#include "ee_assert.h"
#endif /* __ASSERT__ */

#endif /* __INCLUDE_PKG_EE_H__ */
